export const API_LOGIN = '/_api/login'
export const API_LOGOUT = '/_api/logout'
export const API_GET_ME = '/_api/users/me'
export const API_GET_POSTS = '/_api/posts/'
export const API_GET_CATEGORIES = '/_api/categories/'
export const API_GET_PRESENTATIONS = '/_api/presentations/'
export const API_GET_BOOK_AUTHORS = '/_api/book-authors/'
export const API_MARKDOWN_TO_HTML = '/_api/markdown-to-html/'
