"""Add locale field

Revision ID: 1123af112b8b
Revises: 19e1958b2b4
Create Date: 2016-04-18 15:47:43.079177

"""

# revision identifiers, used by Alembic.
revision = '1123af112b8b'
down_revision = '19e1958b2b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('locale', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'locale')
    ### end Alembic commands ###
