"""Add download_url field

Revision ID: 39539a1328a
Revises: 30e199508a1
Create Date: 2013-12-30 00:47:03.607025

"""

# revision identifiers, used by Alembic.
revision = '39539a1328a'
down_revision = '30e199508a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('books', sa.Column('download_url', sa.Text(), nullable=True))
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('books', 'download_url')
    op.alter_column('authors', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
