"""Add presentation

Revision ID: a8085e876605
Revises: 53a7e29a7472
Create Date: 2019-01-28 21:23:17.365934

"""

# revision identifiers, used by Alembic.
revision = 'a8085e876605'
down_revision = '53a7e29a7472'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=400), nullable=False),
    sa.Column('url', sa.Unicode(length=400), nullable=False),
    sa.Column('event', sa.Unicode(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presentations')
    # ### end Alembic commands ###
