"""Lengthen password field

Revision ID: ac963e899f34
Revises: a8085e876605
Create Date: 2019-11-17 13:57:19.063559

"""

# revision identifiers, used by Alembic.
revision = "ac963e899f34"
down_revision = "a8085e876605"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=80),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=80),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
