server {
	root /usr/share/nginx/www;
	index index.html index.htm;

    server_name img.quan.hoabinh.vn;

    access_log /var/log/nginx/img.quan.hoabinh.vn/access.log;
    error_log /var/log/nginx/img.quan.hoabinh.vn/error.log;

    location / {
        proxy_pass https://quan-images.b-cdn.net;
        proxy_set_header Host quan-images.b-cdn.net;
        # Do NOT forward X-Forwarded-For / X-Real-IP / X-Forwarded-Proto
        # Bunny's edge sets its own and blocks requests that arrive with them

        # Forward browser headers for content negotiation (nice to have, but not a must)
        proxy_set_header User-Agent $http_user_agent;
        proxy_set_header Accept $http_accept;
        proxy_set_header Accept-Language $http_accept_language;
        proxy_set_header Accept-Encoding $http_accept_encoding;
        proxy_set_header Referer $http_referer;

    }

    listen 80;
    listen [::]:80;
	listen 443 ssl;
	listen [::]:443 ssl;
	http2 on;

	ssl_certificate /etc/letsencrypt/live/img.quan.hoabinh.vn/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/img.quan.hoabinh.vn/privkey.pem;
}
