# AUTOGENERATED FROM 'queries/list_post_containing_imgur.edgeql' WITH:
#     $ gel-py --dir queries/ --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid

import gel


@dataclasses.dataclass
class ListPostContainingImgurResult:
    id: uuid.UUID
    body: str | None


async def list_post_containing_imgur(
    executor: gel.AsyncIOExecutor,
) -> list[ListPostContainingImgurResult]:
    return await executor.query(
        """\
        SELECT BlogPost { id, body } FILTER contains(.body, 'imgur');\
        """,
    )
