"""Add html field

Revision ID: 19e1958b2b4
Revises: 39539a1328a
Create Date: 2015-09-11 01:13:11.519881

"""

# revision identifiers, used by Alembic.
revision = '19e1958b2b4'
down_revision = '39539a1328a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'html')
    ### end Alembic commands ###
