"""Add meta fields

Revision ID: 53a7e29a7472
Revises: 1123af112b8b
Create Date: 2017-08-16 14:35:02.296168

"""

# revision identifiers, used by Alembic.
revision = '53a7e29a7472'
down_revision = '1123af112b8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('og_image', sa.String(length=100), nullable=True))
    op.add_column('entries', sa.Column('seo_description', sa.String(length=200), nullable=True))
    op.add_column('entries', sa.Column('seo_keywords', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'seo_keywords')
    op.drop_column('entries', 'seo_description')
    op.drop_column('entries', 'og_image')
    # ### end Alembic commands ###
