"""Increase field length

Revision ID: 6c763e55b763
Revises: ac963e899f34
Create Date: 2022-02-20 18:13:38.569576

"""

# revision identifiers, used by Alembic.
revision = '6c763e55b763'
down_revision = 'ac963e899f34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'og_image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('entries', 'seo_description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'seo_description',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('entries', 'og_image',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
